-- Ideas & requests — one thing. Run once in the Supabase SQL Editor, after
-- 004-membership-teams.sql. Safe to re-run. Then copy the forum-era ideas in
-- with: node --env-file=.env scripts/import-ideas-to-supabase.mjs
--
-- A signed-in member sends an idea or request from /anetaresohu/kerkesat/
-- ("Idetë & kërkesat") and follows it there. No review step: if the member
-- chose public (wants_public) it goes straight to the public board at
-- /projektet/ide/ ("Ndaj Ide") as 'published'; otherwise it's 'hidden', between
-- the member and the IB team (e.g. "I'd like to organise in my city"). Admins
-- can still hide a published one afterwards, and reply with admin_note, which
-- only the author and admins see. The author (or an admin) marks it resolved
-- or removes it.
--
-- The public reads only the public_ideas view (published rows, public
-- columns). `name` and `contact_email` are public on published ideas — the
-- author chooses on submit whether to fill them; without an email, replies go
-- to the org inbox.

create table if not exists ideas (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null check (length(title) between 3 and 160),
  description text not null default '' check (length(description) <= 50000),   -- Markdown (forum archive posts run past submit_idea's 20000 cap)
  area text check (area is null or area in ('Kërkoj punë', 'Ofroj ndihmë', 'Grup aktiviteti', 'Bashkëpunim')),
  name text,
  contact_email text,
  member_id bigint references members(id) on delete set null,
  wants_public boolean not null default true,
  status text not null default 'pending' check (status in ('pending', 'published', 'hidden')),
  resolved boolean not null default false,
  admin_note text check (length(admin_note) <= 2000),
  source text not null default 'site',    -- 'forum' for the migrated archive
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table ideas drop constraint if exists ideas_description_check;
alter table ideas add constraint ideas_description_check check (length(description) <= 50000);
create index if not exists ideas_member_id on ideas (member_id);
-- From before ideas skipped review: publish what was waiting, as its author asked.
update ideas set status = case when wants_public then 'published' else 'hidden' end where status = 'pending';
alter table ideas enable row level security;
drop policy if exists "ideas: own, admins all" on ideas;
create policy "ideas: own, admins all" on ideas for select to authenticated using (can_edit_member(member_id));

create or replace view public_ideas as
select id, slug, title, description, area, name, contact_email, resolved, source, created_at
from ideas where status = 'published';
grant select on public_ideas to anon, authenticated;

-- "Takim për studentët në Milano!" → "takim-per-studentet-ne-milano", with a
-- -2, -3… suffix when taken.
create or replace function idea_slug(p_title text) returns text
language plpgsql stable security definer set search_path = public as $$
declare
  v_base text := trim(both '-' from regexp_replace(lower(translate(p_title, 'ëËçÇ', 'eEcC')), '[^a-z0-9]+', '-', 'g'));
  v_slug text;
  v_n int := 1;
begin
  v_base := left(coalesce(nullif(v_base, ''), 'ide'), 80);
  v_slug := v_base;
  while exists (select 1 from ideas where slug = v_slug) loop
    v_n := v_n + 1;
    v_slug := v_base || '-' || v_n;
  end loop;
  return v_slug;
end $$;

create or replace function submit_idea(p jsonb) returns text
language plpgsql security definer set search_path = public as $$
declare
  v_member members%rowtype;
  v_title text := trim(coalesce(p ->> 'title', ''));
  v_area text := nullif(p ->> 'area', '');
  v_slug text;
begin
  select * into v_member from members where current_email() <> '' and lower(email) = current_email() order by id limit 1;
  if v_member.id is null then
    raise exception 'Emaili yt nuk është i lidhur me asnjë profil anëtari.' using errcode = '42501';
  end if;
  if length(v_title) < 3 or length(v_title) > 160 then
    raise exception 'Titulli duhet të ketë 3–160 shkronja.';
  end if;
  if v_area is not null and v_area not in ('Kërkoj punë', 'Ofroj ndihmë', 'Grup aktiviteti', 'Bashkëpunim') then
    raise exception 'Kategori e panjohur.';
  end if;
  if (select count(*) from ideas where member_id = v_member.id and created_at > now() - interval '1 day') >= 10 then
    raise exception 'Ke dërguar shumë sot — provo sërish nesër.';
  end if;
  v_slug := idea_slug(v_title);
  insert into ideas (slug, title, description, area, name, contact_email, member_id, wants_public, status)
  values (
    v_slug, v_title, left(trim(coalesce(p ->> 'description', '')), 20000), v_area,
    case when coalesce((p ->> 'show_name')::boolean, false) then v_member.name end,
    case when coalesce((p ->> 'show_email')::boolean, false) then v_member.email end,
    v_member.id, coalesce((p ->> 'wants_public')::boolean, true),
    case when coalesce((p ->> 'wants_public')::boolean, true) then 'published' else 'hidden' end
  );
  return v_slug;
end $$;

-- Author or admin: open / resolved.
create or replace function set_idea_resolved(p_id bigint, p_resolved boolean) returns void
language plpgsql security definer set search_path = public as $$
begin
  update ideas set resolved = p_resolved, updated_at = now() where id = p_id and can_edit_member(member_id);
  if not found then
    raise exception 'Vetëm autori ose një admin mund ta ndryshojë këtë.' using errcode = '42501';
  end if;
end $$;

-- Admin only: publish / hide / back to pending, plus the reply to the author.
create or replace function update_idea_admin(p_id bigint, p_status text, p_admin_note text) returns void
language plpgsql security definer set search_path = public as $$
begin
  if not is_admin() then
    raise exception 'Vetëm adminët mund ta ndryshojnë statusin.' using errcode = '42501';
  end if;
  if p_status not in ('pending', 'published', 'hidden') then
    raise exception 'Status i panjohur.';
  end if;
  update ideas
  set status = p_status, admin_note = nullif(left(trim(coalesce(p_admin_note, '')), 2000), ''), updated_at = now()
  where id = p_id;
end $$;

-- The author can remove their own; admins can delete any.
create or replace function delete_idea(p_id bigint) returns void
language plpgsql security definer set search_path = public as $$
begin
  delete from ideas i
  where i.id = p_id and (is_admin() or (i.member_id is not null and can_edit_member(i.member_id)));
  if not found then
    raise exception 'Kjo nuk mund të hiqet më.' using errcode = '42501';
  end if;
end $$;

revoke all on function idea_slug(text) from public, anon, authenticated;
revoke all on function submit_idea(jsonb) from public, anon;
revoke all on function set_idea_resolved(bigint, boolean) from public, anon;
revoke all on function update_idea_admin(bigint, text, text) from public, anon;
revoke all on function delete_idea(bigint) from public, anon;
grant execute on function submit_idea(jsonb) to authenticated;
grant execute on function set_idea_resolved(bigint, boolean) to authenticated;
grant execute on function update_idea_admin(bigint, text, text) to authenticated;
grant execute on function delete_idea(bigint) to authenticated;

-- An earlier draft of this file created a separate member_requests table
-- (never used for real — it was empty when this replaced it).
drop function if exists submit_member_request(text, text, text);
drop function if exists update_member_request(bigint, text, text);
drop function if exists delete_member_request(bigint);
drop table if exists member_requests;
