-- NGOs & businesses — the one list behind /partneret/ and /bizneset/. Run once
-- in the Supabase SQL Editor, after 005-ideas.sql. Safe to re-run. Then copy
-- the old CSV lists in with:
--   node --env-file=.env scripts/import-organizations-to-supabase.mjs
--
-- A signed-in member adds an NGO or a business they run or belong to from
-- /anetaresohu/organizatat/ ("OJF & biznese") and follows it there. It starts
-- as 'pending'; an admin publishes it (or hides it) and can reply with
-- admin_note, which only the author and admins see. Published ones show on
-- /partneret/ and /bizneset/ at the next build — scripts/sync-organizations-supabase.mjs
-- writes src/data/organizations.json. The member who added it is listed as a
-- related member. An author's edit sends a published entry back to 'pending'.
--
-- The curated columns (sponsor, collaborations, related_*, other_categories)
-- are IB's side of the relationship: members can't set them, admins edit them
-- in the Supabase Table Editor.
--
-- Logos go to the same `avatars` bucket as profile photos (002-editing.sql),
-- in the uploader's own folder. The imported ones are /assets/… paths.

create table if not exists organizations (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('ngo', 'business')),
  name text not null check (length(name) between 2 and 120),
  category text not null,
  stage text check (stage is null or stage in ('startup', 'established', 'diaspora')),   -- businesses only
  city text,
  country text,
  description text not null default '' check (length(description) <= 1000),
  website text,
  linkedin text,
  instagram text,
  logo text,
  member_id bigint references members(id) on delete set null,
  status text not null default 'pending' check (status in ('pending', 'published', 'hidden')),
  admin_note text check (length(admin_note) <= 2000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists organizations_member_id on organizations (member_id);
alter table organizations enable row level security;
drop policy if exists "organizations: own, admins all" on organizations;
create policy "organizations: own, admins all" on organizations for select to authenticated using (can_edit_member(member_id));

alter table organizations add column if not exists other_categories text[] not null default '{}';   -- NGOs: beyond `category`
alter table organizations add column if not exists sponsor boolean not null default false;
alter table organizations add column if not exists collaborations text[] not null default '{}';     -- NGOs: collaborationTypeOptions in partners.ts
alter table organizations add column if not exists related_members text[] not null default '{}';    -- usernames
alter table organizations add column if not exists related_cities text[] not null default '{}';
alter table organizations add column if not exists related_partners text[] not null default '{}';   -- other NGOs, by name
alter table organizations add column if not exists source text not null default 'site';             -- 'csv' for the imported lists

-- `username` links the entry to its author's directory profile (only when that
-- profile is itself public).
drop view if exists public_organizations;
create view public_organizations as
select o.id, o.kind, o.name, o.category, o.other_categories, o.stage, o.city, o.country, o.description,
  o.website, o.linkedin, o.instagram, o.logo, o.sponsor, o.collaborations,
  o.related_members, o.related_cities, o.related_partners, m.username, o.created_at
from organizations o
left join members m on m.id = o.member_id and m.status = 'ok'
where o.status = 'published';
grant select on public_organizations to anon, authenticated;

-- Add (p_id null) or edit. Members edit their own; admins any, keeping its status.
create or replace function save_organization(p_id bigint, p jsonb) returns bigint
language plpgsql security definer set search_path = public as $$
declare
  v_member members%rowtype;
  v_kind text := p ->> 'kind';
  v_category text := coalesce(p ->> 'category', '');
  v_link text;
  v_id bigint;
begin
  select * into v_member from members where current_email() <> '' and lower(email) = current_email() order by id limit 1;
  if v_member.id is null and not is_admin() then
    raise exception 'Emaili yt nuk është i lidhur me asnjë profil anëtari.' using errcode = '42501';
  end if;
  if p_id is not null and not exists (select 1 from organizations where id = p_id and can_edit_member(member_id)) then
    raise exception 'Vetëm autori ose një admin mund ta ndryshojë këtë.' using errcode = '42501';
  end if;
  if v_kind is null or v_kind not in ('ngo', 'business') then
    raise exception 'Zgjidh OJF ose biznes.';
  end if;
  if length(trim(coalesce(p ->> 'name', ''))) not between 2 and 120 then
    raise exception 'Emri duhet të ketë 2–120 shkronja.';
  end if;
  if (v_kind = 'ngo' and v_category not in ('advocacy', 'education', 'culture', 'environment', 'diaspora'))
    or (v_kind = 'business' and v_category not in ('technology', 'architecture', 'health', 'finance', 'business-development', 'other')) then
    raise exception 'Kategori e panjohur.';
  end if;
  if v_kind = 'business' and coalesce(p ->> 'stage', '') not in ('startup', 'established', 'diaspora') then
    raise exception 'Zgjidh fazën e biznesit.';
  end if;
  if length(coalesce(p ->> 'description', '')) > 1000 then
    raise exception 'Përshkrimi është shumë i gjatë (maks. 1000 shkronja).';
  end if;
  foreach v_link in array array[p ->> 'website', p ->> 'linkedin', p ->> 'instagram'] loop
    if coalesce(v_link, '') <> '' and v_link !~* '^https?://[^\s<>"]+$' then
      raise exception 'Linku duhet të fillojë me https:// (%).', v_link;
    end if;
  end loop;
  if coalesce(p ->> 'logo', '') <> '' and p ->> 'logo' !~ '^https://[^\s<>"]+/storage/v1/object/public/avatars/' and not is_admin() then
    raise exception 'Logoja duhet të ngarkohet nga kjo faqe.';
  end if;

  if p_id is null then
    if (select count(*) from organizations where member_id = v_member.id and created_at > now() - interval '1 day') >= 10 then
      raise exception 'Ke dërguar shumë sot — provo sërish nesër.';
    end if;
    insert into organizations (kind, name, category, member_id) values (v_kind, trim(p ->> 'name'), v_category, v_member.id)
    returning id into v_id;
  else
    v_id := p_id;
  end if;

  update organizations set
    kind = v_kind,
    name = trim(p ->> 'name'),
    category = v_category,
    stage = case when v_kind = 'business' then p ->> 'stage' end,
    city = nullif(trim(p ->> 'city'), ''),
    country = nullif(trim(p ->> 'country'), ''),
    description = trim(coalesce(p ->> 'description', '')),
    website = nullif(trim(p ->> 'website'), ''),
    linkedin = nullif(trim(p ->> 'linkedin'), ''),
    instagram = nullif(trim(p ->> 'instagram'), ''),
    logo = nullif(p ->> 'logo', ''),
    status = case when is_admin() then status else 'pending' end,
    updated_at = now()
  where id = v_id;
  return v_id;
end $$;

-- Admin only: publish / hide / back to pending, plus the reply to the author.
create or replace function update_organization_admin(p_id bigint, p_status text, p_admin_note text) returns void
language plpgsql security definer set search_path = public as $$
begin
  if not is_admin() then
    raise exception 'Vetëm adminët mund ta ndryshojnë statusin.' using errcode = '42501';
  end if;
  if p_status not in ('pending', 'published', 'hidden') then
    raise exception 'Status i panjohur.';
  end if;
  update organizations
  set status = p_status, admin_note = nullif(left(trim(coalesce(p_admin_note, '')), 2000), ''), updated_at = now()
  where id = p_id;
end $$;

-- The author can remove their own; admins can delete any.
create or replace function delete_organization(p_id bigint) returns void
language plpgsql security definer set search_path = public as $$
begin
  delete from organizations o
  where o.id = p_id and (is_admin() or (o.member_id is not null and can_edit_member(o.member_id)));
  if not found then
    raise exception 'Kjo nuk mund të hiqet më.' using errcode = '42501';
  end if;
end $$;

revoke all on function save_organization(bigint, jsonb) from public, anon;
revoke all on function update_organization_admin(bigint, text, text) from public, anon;
revoke all on function delete_organization(bigint) from public, anon;
grant execute on function save_organization(bigint, jsonb) to authenticated;
grant execute on function update_organization_admin(bigint, text, text) to authenticated;
grant execute on function delete_organization(bigint) to authenticated;
