-- Following + posts (the LinkedIn-like part). Run once in the Supabase SQL
-- Editor, after 006-organizations.sql. Safe to re-run.
--
-- Following is one-way, like LinkedIn's "Follow": no request to accept.
-- Follower/following *counts* are public (shown on /anetaret/<slug>/); who
-- follows whom is seen only by the member themself, on /anetaresohu/rrjeti/.
--
-- Posts are short plain-text updates. They're public, like LinkedIn posts:
-- the public_member_posts view shows them on the member's profile page and in
-- the feed on /anetaresohu/rrjeti/. The author or an admin can delete one.
--
-- Only approved members (status = 'ok') can follow or post — pending ones
-- have no public profile to link to yet.

create table if not exists member_follows (
  follower_id bigint not null references members(id) on delete cascade,
  followee_id bigint not null references members(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, followee_id),
  check (follower_id <> followee_id)
);
create index if not exists member_follows_followee on member_follows (followee_id);
alter table member_follows enable row level security;   -- no policies: functions below only

create table if not exists member_posts (
  id bigint generated by default as identity primary key,
  member_id bigint not null references members(id) on delete cascade,
  body text not null check (length(trim(body)) between 1 and 3000),
  created_at timestamptz not null default now()
);
create index if not exists member_posts_member_id on member_posts (member_id, created_at desc);
alter table member_posts enable row level security;     -- no policies: read through the view

-- The signed-in user's approved member row, or null.
create or replace function my_member_id() returns bigint
language sql stable security definer set search_path = public as $$
  select id from members where current_email() <> '' and lower(email) = current_email() and status = 'ok' order by id limit 1
$$;

-- ── Following ────────────────────────────────────────────────────────────────
create or replace function set_follow(p_username text, p_follow boolean) returns void
language plpgsql security definer set search_path = public as $$
declare
  v_me bigint := my_member_id();
  v_them bigint;
begin
  if v_me is null then
    raise exception 'Vetëm anëtarët e aprovuar mund të ndjekin të tjerë.' using errcode = '42501';
  end if;
  select id into v_them from members where username = p_username and status = 'ok';
  if v_them is null then raise exception 'Ky anëtar nuk u gjet.'; end if;
  if v_them = v_me then raise exception 'Nuk mund të ndjekësh veten.'; end if;
  if p_follow then
    insert into member_follows (follower_id, followee_id) values (v_me, v_them) on conflict do nothing;
  else
    delete from member_follows where follower_id = v_me and followee_id = v_them;
  end if;
end $$;

-- Public counts for a profile page, plus whether the caller follows them.
create or replace function follow_stats(p_username text) returns json
language sql stable security definer set search_path = public as $$
  select json_build_object(
    'followers', (select count(*) from member_follows f join members x on x.id = f.follower_id and x.status = 'ok' where f.followee_id = m.id),
    'following', (select count(*) from member_follows f join members x on x.id = f.followee_id and x.status = 'ok' where f.follower_id = m.id),
    'is_following', exists (select 1 from member_follows where follower_id = my_member_id() and followee_id = m.id),
    'is_me', m.id = my_member_id()
  )
  from members m where m.username = p_username and m.status = 'ok'
$$;

-- The caller's own network, for /anetaresohu/rrjeti/: usernames only — the
-- page joins them with public_member_profiles.
create or replace function my_network() returns json
language sql stable security definer set search_path = public as $$
  select json_build_object(
    'username', m.username,
    'following', coalesce((select json_agg(x.username order by f.created_at desc) from member_follows f join members x on x.id = f.followee_id and x.status = 'ok' where f.follower_id = m.id), '[]'),
    'followers', coalesce((select json_agg(x.username order by f.created_at desc) from member_follows f join members x on x.id = f.follower_id and x.status = 'ok' where f.followee_id = m.id), '[]')
  )
  from members m where m.id = my_member_id()
$$;

-- ── Posts ────────────────────────────────────────────────────────────────────
create or replace function create_post(p_body text) returns bigint
language plpgsql security definer set search_path = public as $$
declare
  v_me bigint := my_member_id();
  v_id bigint;
begin
  if v_me is null then
    raise exception 'Vetëm anëtarët e aprovuar mund të postojnë.' using errcode = '42501';
  end if;
  if length(trim(coalesce(p_body, ''))) = 0 then raise exception 'Postimi është bosh.'; end if;
  if length(trim(p_body)) > 3000 then raise exception 'Postimi është shumë i gjatë (maks. 3000 shkronja).'; end if;
  if (select count(*) from member_posts where member_id = v_me and created_at > now() - interval '1 day') >= 20 then
    raise exception 'Ke arritur kufirin prej 20 postimesh në ditë.';
  end if;
  insert into member_posts (member_id, body) values (v_me, trim(p_body)) returning id into v_id;
  return v_id;
end $$;

create or replace function delete_post(p_id bigint) returns void
language plpgsql security definer set search_path = public as $$
begin
  delete from member_posts where id = p_id and (is_admin() or member_id = my_member_id());
  if not found then raise exception 'Nuk ke të drejtë ta fshish këtë postim.' using errcode = '42501'; end if;
end $$;

-- Runs with the owner's rights, like public_member_profiles: approved
-- members' posts with just enough of the author to render them.
create or replace view public_member_posts as
select p.id, p.body, p.created_at, m.username, m.name, m.headline, m.avatar
from member_posts p join members m on m.id = p.member_id
where m.status = 'ok';
grant select on public_member_posts to anon, authenticated;

revoke all on function set_follow(text, boolean), my_network(), create_post(text), delete_post(bigint) from public, anon;
grant execute on function set_follow(text, boolean), my_network(), create_post(text), delete_post(bigint) to authenticated;
grant execute on function follow_stats(text), my_member_id() to anon, authenticated;
