-- Standardized offers from represented organizations. Run after 014-subscriptions.sql.
-- Projects, volunteer calls, benefits and collaboration requests all use one
-- model and become notifications for members following the organization.

create table if not exists organization_offers (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references organizations(id) on delete cascade,
  kind text not null check (kind in ('project', 'volunteer', 'benefit', 'collaboration')),
  title text not null check (length(trim(title)) between 3 and 160),
  description text not null check (length(trim(description)) between 10 and 2000),
  url text,
  expires_at date,
  status text not null default 'pending' check (status in ('pending', 'published', 'hidden')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists organization_offers_org on organization_offers (organization_id, created_at desc);
alter table organization_offers enable row level security;
drop policy if exists "offers: represented organizations" on organization_offers;
create policy "offers: represented organizations" on organization_offers for select to authenticated
using (exists (select 1 from organizations o where o.id = organization_id and can_edit_member(o.member_id)));

create or replace view public_organization_offers as
select f.id, f.organization_id, f.kind, f.title, f.description, f.url, f.expires_at, f.created_at,
  o.name as organization_name, o.kind as organization_kind, o.logo as organization_logo
from organization_offers f join organizations o on o.id = f.organization_id
where f.status = 'published' and o.status = 'published' and (f.expires_at is null or f.expires_at >= current_date);
grant select on public_organization_offers to anon, authenticated;

create or replace function save_organization_offer(p_id bigint, p jsonb) returns bigint
language plpgsql security definer set search_path = public as $$
declare
  v_me bigint := my_member_id();
  v_org bigint := (p ->> 'organization_id')::bigint;
  v_kind text := p ->> 'kind';
  v_url text := nullif(trim(p ->> 'url'), '');
  v_id bigint;
begin
  if v_me is null or not exists (select 1 from organizations o where o.id = v_org and (is_admin() or o.member_id = v_me)) then
    raise exception 'Nuk ke të drejtë të publikosh për këtë subjekt.' using errcode = '42501';
  end if;
  if p_id is not null and not exists (select 1 from organization_offers f join organizations o on o.id = f.organization_id where f.id = p_id and (is_admin() or o.member_id = v_me)) then
    raise exception 'Nuk ke të drejtë ta ndryshosh këtë ofertë.' using errcode = '42501';
  end if;
  if v_kind not in ('project', 'volunteer', 'benefit', 'collaboration') then raise exception 'Lloj oferte i panjohur.'; end if;
  if length(trim(coalesce(p ->> 'title', ''))) not between 3 and 160 then raise exception 'Titulli duhet të ketë 3–160 shkronja.'; end if;
  if length(trim(coalesce(p ->> 'description', ''))) not between 10 and 2000 then raise exception 'Përshkrimi duhet të ketë 10–2000 shkronja.'; end if;
  if v_url is not null and v_url !~* '^https?://[^\s<>"]+$' then raise exception 'Linku duhet të fillojë me https://.'; end if;
  if p_id is null then
    insert into organization_offers (organization_id, kind, title, description) values (v_org, v_kind, trim(p ->> 'title'), trim(p ->> 'description')) returning id into v_id;
  else v_id := p_id; end if;
  update organization_offers f set organization_id = v_org, kind = v_kind, title = trim(p ->> 'title'), description = trim(p ->> 'description'), url = v_url,
    expires_at = nullif(p ->> 'expires_at', '')::date,
    status = case when is_admin() then f.status when exists (select 1 from organizations o where o.id = v_org and o.status = 'published') then 'published' else 'pending' end,
    updated_at = now() where f.id = v_id;
  return v_id;
end $$;

create or replace function delete_organization_offer(p_id bigint) returns void
language plpgsql security definer set search_path = public as $$
begin
  delete from organization_offers f using organizations o
  where f.id = p_id and o.id = f.organization_id and (is_admin() or o.member_id = my_member_id());
  if not found then raise exception 'Kjo ofertë nuk mund të hiqet.' using errcode = '42501'; end if;
end $$;

-- Extend the existing topic subscription model with represented organizations.
alter table member_subscriptions drop constraint if exists member_subscriptions_kind_check;
alter table member_subscriptions add constraint member_subscriptions_kind_check check (kind in ('city', 'field', 'organization'));

create or replace function set_subscription(p_kind text, p_value text, p_on boolean) returns void
language plpgsql security definer set search_path = public as $$
declare v_me bigint := my_member_id(); v_value text := trim(coalesce(p_value, ''));
begin
  if v_me is null then raise exception 'Vetëm anëtarët e aprovuar mund të ndjekin tema.' using errcode = '42501'; end if;
  if p_kind not in ('city', 'field', 'organization') or v_value = '' or length(v_value) > 80 then raise exception 'Zgjedhje e pavlefshme.'; end if;
  if p_kind = 'field' and v_value not in (select name from categories) then raise exception 'Kjo fushë nuk ekziston.'; end if;
  if p_kind = 'organization' and not exists (select 1 from organizations where id::text = v_value and status = 'published') then raise exception 'Ky subjekt nuk ekziston.'; end if;
  if p_on then
    if not exists (select 1 from member_subscriptions where member_id = v_me and kind = p_kind and value = v_value)
      and (select count(*) from member_subscriptions where member_id = v_me) >= 50 then raise exception 'Mund të ndjekësh deri në 50 tema.'; end if;
    insert into member_subscription_reads (member_id) values (v_me) on conflict do nothing;
    insert into member_subscriptions (member_id, kind, value) values (v_me, p_kind, v_value) on conflict do nothing;
  else delete from member_subscriptions where member_id = v_me and kind = p_kind and value = v_value; end if;
end $$;

revoke all on function save_organization_offer(bigint, jsonb), delete_organization_offer(bigint) from public, anon;
grant execute on function save_organization_offer(bigint, jsonb), delete_organization_offer(bigint) to authenticated;
